### ISSUE TITLE
Superuser.apk v2.3.6.1 not granting root to my application (in development)

### ISSUE THREAD

**Issue by cbuchner1** [ChainsDD/Superuser#10]
Superuser works just fine and grants some applications root privileges.

Bot now I am creating my own App in Eclipse, which does need root permissions at one point. I called it AutoMarket, and it the code gets currently signed by Eclipse/ADT (but I understand that this is only test signing keys). So this can't be published to the Android Market as is.

I used "adt install AutoMarket.apk" to install my app on my device (ZT-180 android tablet)

Internally the app does the usual "Runtime.getRuntime().exec("su something") and then waits for the return code and captures stderr/stdout.

The problem is that I do not get any popup by Superuser.apk asking me whether or not I am supposed to give root permissions to AutoMarket. Instead I get this in the logcat buffer:

W/su: ( 3178) request rejected (0->0  /system/bin/sh)

and the exit code and stderr output are as follows:
255
Permission denied

What could be wrong here? Right now I perform all actions in my UI thread (which is bad practice, I know). Could this be blocking Superuser from showing the prompt? Or is it something else, for example the test signing keys that are used?

**Comment by djense** [comment]
I am having the same problem with my device. The logcat shows :
E/su      (  400): stat failed with 2: No such file or directory  
W/su      (  400): request rejected (10021->0 /system/bin/sh)  
su is there in the path :
/data/data # busybox which su  
/system/xbin/su  
/data/data # su -v  
2.3.1-cd  
(looks like that version string was not updated in 2.3.6.1-cd ?)

Edit : sbaranov helped me fix the problem, I was "installing" SuperUser.apk instead of pushing it to /system/app...

**Comment by cbuchner1** [comment]
Well my problem also went away now, but I can't pinpoint what caused it in the first place. Closing this issue.
